{% set name = "python-cinderclient" %}
{% set version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2257ab22da4472449ddc752551341226da2bfc16b67d9869cdeaf45ba86bfaa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cinder = cinderclient.shell:main

requirements:
  host:
    - pbr
    - pip
    - python >=3.6
  run:
    - pbr
    - prettytable >=0.7.2
    - keystoneauth1 >=4.3.1
    - simplejson >=3.5.1
    - oslo.i18n >=5.0.1
    - oslo.utils >=4.8.0
    - python >=3.6
    - requests >=2.25.1
    - stevedore >=3.3.0

test:
  imports:
    - cinderclient

about:
  home: https://docs.openstack.org/python-cinderclient/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: OpenStack Block Storage API Client Library
  doc_url: https://docs.openstack.org/python-cinderclient/latest/
  dev_url: https://opendev.org/openstack/python-cinderclient

extra:
  recipe-maintainers:
    - tschoonj
